### ISSUE TITLE
Where and How to insert these two links:

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorlayer/awesome-tensorlayer#2]
I don't really kn ow what to do with them and where it would be most appropriate.

 - [DAGGER](https://www.cs.cmu.edu/%7Esross1/publications/Ross-AIStats11-NoRegret.pdf) for ([Gym Torcs](https://github.com/ugo-nama-kun/gym_torcs)) by [zsdonghao](https://github.com/zsdonghao/Imitation-Learning-Dagger-Torcs).
 
 - [TRPO](https://arxiv.org/abs/1502.05477) for continuous and discrete action space by [jjkke88](https://github.com/jjkke88/RL_toolbox).

Maybe @zsdonghao you can make a commit adding these two where you think it would be best.

**Comment by zsdonghao** [comment]
@DEKHTIARJonathan just simply insert into Reinforcement Learning

**Comment by DEKHTIARJonathan** [comment]
I'll do this ;)
